"use client";

import { useEffect, useMemo, useState } from "react";

type P="A"|"B"; type T="attack"|"defense"|"magic";
type Die={id:string,type:T,value:number};
type Cost={sum?:number,exactSum?:number,count?:number,types?:Partial<Record<T,number>>,same?:boolean,values?:number[]};
type Ability={name:string,text:string,cost:Cost,kind:"damage"|"heal"|"damageSelf"|"steal"|"adjustPool",amount?:number,self?:number,bonusPool?:{type:T,count:number,bonus:number},woundedBonus?:number};
type Card={id:string,name:string,faction:string,init:number,hp:number,glory:number,dice:T[],abilities:Ability[],passive?:"punish3"|"inherit2"|"tax3"};
type C={id:string,owner:P,card:Card,hp:number,alive:boolean,dice:Die[]};
type G={cards:Card[],creatures:C[],pool:Die[],queue:string[],active:string|null,needsDie:boolean,used:boolean,round:number,log:string[],rng:number,nextDie:number,nextC:number,done:boolean};

const I:Record<T,string>={attack:"⚔",defense:"🛡",magic:"✦"};
const F=[1,1,2,2,3,3];
const CARDS:Card[]=[
{id:"punisher",name:"Каратель силы",faction:"Алый легион",init:7,hp:3,glory:2,dice:["attack","defense"],passive:"punish3",abilities:[{name:"Приговор",text:"⚔4: 2 урона раненой цели.",cost:{sum:4,types:{attack:1}},kind:"damage",amount:2,woundedBonus:1}]},
{id:"raider",name:"Штурмовой налётчик",faction:"Алый легион",init:8,hp:4,glory:2,dice:["attack","attack","magic"],abilities:[{name:"Налёт",text:"⚔3: 1 урон; при 5+ ⚔ в пуле — 2.",cost:{sum:3,types:{attack:1}},kind:"damage",amount:1,bonusPool:{type:"attack",count:5,bonus:1}}]},
{id:"bodyguard",name:"Телохранитель",faction:"Каменный завет",init:6,hp:5,glory:2,dice:["defense","defense","attack"],passive:"inherit2",abilities:[{name:"Прикрыть",text:"🛡3: лечи союзника на 1, получи 1 урон.",cost:{sum:3,types:{defense:1}},kind:"heal",amount:1,self:1}]},
{id:"bastion",name:"Бастион",faction:"Каменный завет",init:1,hp:8,glory:4,dice:["defense","defense","defense"],abilities:[{name:"Укрепиться",text:"🛡3: лечение 1; при 4+ 🛡 в пуле — 2.",cost:{sum:3,types:{defense:1}},kind:"heal",amount:1,bonusPool:{type:"defense",count:4,bonus:1}}]},
{id:"alchemist",name:"Алхимик",faction:"Эфирный конклав",init:8,hp:3,glory:2,dice:["magic","magic","magic","attack"],abilities:[{name:"Катализатор",text:"✨+⚔5: 2 урона и усили один куб пула.",cost:{sum:5,types:{magic:1,attack:1}},kind:"adjustPool",amount:2}]},
{id:"archmage",name:"Архимаг потока",faction:"Эфирный конклав",init:2,hp:5,glory:5,dice:["magic","magic","magic"],abilities:[{name:"Разряд",text:"✨6: 3 урона; при 4+ ✨ в пуле — 4.",cost:{sum:6,types:{magic:1}},kind:"damage",amount:3,bonusPool:{type:"magic",count:4,bonus:1}}]},
{id:"pickpocket",name:"Карманница",faction:"Синдикат Воронов",init:8,hp:3,glory:2,dice:["magic","defense"],abilities:[{name:"Лёгкая рука",text:"✨3: укради вражеский куб 1.",cost:{sum:3,types:{magic:1}},kind:"steal"}]},
{id:"collector",name:"Сборщик долгов",faction:"Синдикат Воронов",init:5,hp:5,glory:3,dice:["attack","attack","magic"],passive:"tax3",abilities:[{name:"Взыскание",text:"⚔+✨5: 2 урона; +1 если у цели есть куб 1.",cost:{sum:5,types:{attack:1,magic:1}},kind:"damage",amount:2}]},
{id:"berserker",name:"Берсерк",faction:"Пепельные кланы",init:6,hp:6,glory:2,dice:["attack","attack","magic"],abilities:[{name:"Ярость",text:"⚔+✨6: 4 урона врагу и 2 себе.",cost:{sum:6,types:{attack:1,magic:1}},kind:"damageSelf",amount:4,self:2}]},
{id:"martyr",name:"Мученик",faction:"Пепельные кланы",init:4,hp:6,glory:4,dice:["defense","defense","attack"],passive:"inherit2",abilities:[{name:"Принять боль",text:"🛡3: лечи союзника на 2, получи 1 урон.",cost:{sum:3,types:{defense:1}},kind:"heal",amount:2,self:1}]},
{id:"counter",name:"Счётчик",faction:"Часовая гильдия",init:5,hp:5,glory:3,dice:["attack","defense","magic"],abilities:[{name:"Ровно пять",text:"Ровно 2 куба суммой 5: 3 урона.",cost:{exactSum:5,count:2},kind:"damage",amount:3},{name:"Ровно три",text:"Ровно 2 куба суммой 3: лечение 2.",cost:{exactSum:3,count:2},kind:"heal",amount:2}]},
{id:"sequence",name:"Мастер последовательностей",faction:"Часовая гильдия",init:3,hp:5,glory:4,dice:["attack","defense","magic","magic"],abilities:[{name:"Последовательность",text:"Кубы 1,2,3: 3 урона.",cost:{count:3,values:[1,2,3]},kind:"damage",amount:3}]}
];

function rand(s:number):[number,number]{let v=s>>>0;v+=0x6d2b79f5;let t=v;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return[((t^(t>>>14))>>>0)/4294967296,v>>>0]}
function shuf<T>(a:T[],s:number):[T[],number]{const x=[...a];for(let i=x.length-1;i>0;i--){const[r,n]=rand(s);s=n;const j=Math.floor(r*(i+1));[x[i],x[j]]=[x[j],x[i]]}return[x,s]}
function q(cs:C[]){return cs.filter(c=>c.alive).sort((a,b)=>b.card.init-a.card.init||a.card.glory-b.card.glory||a.owner.localeCompare(b.owner)).map(c=>c.id)}
function combos<T>(a:T[]){const r:T[][]=[];for(let m=1;m<(1<<a.length);m++){const c:T[]=[];for(let i=0;i<a.length;i++)if(m&(1<<i))c.push(a[i]);r.push(c)}return r}
function pay(c:C,a:Ability){return combos(c.dice).filter(x=>!a.cost.count||x.length===a.cost.count).filter(x=>a.cost.exactSum===undefined||x.reduce((n,d)=>n+d.value,0)===a.cost.exactSum).filter(x=>x.reduce((n,d)=>n+d.value,0)>=(a.cost.sum??0)).filter(x=>Object.entries(a.cost.types??{}).every(([t,n])=>x.filter(d=>d.type===t).length>=(n??0))).filter(x=>!a.cost.same||new Set(x.map(d=>d.value)).size===1).filter(x=>!a.cost.values||[...x.map(d=>d.value)].sort().join()===[...a.cost.values].sort().join()).sort((a,b)=>a.reduce((n,d)=>n+d.value,0)-b.reduce((n,d)=>n+d.value,0))[0]}
function creature(g:G,id:string|null){return id?g.creatures.find(c=>c.id===id)||null:null}
function upd(g:G,id:string,f:(c:C)=>C){return{...g,creatures:g.creatures.map(c=>c.id===id?f(c):c)}}
function note(g:G,s:string){return{...g,log:[s,...g.log].slice(0,24)}}
function effectLabel(ab:Ability){if(ab.kind==="damage")return`⚔ ${ab.amount??0} урона`;if(ab.kind==="heal")return`♥ ${ab.amount??0} лечения${ab.self?` · 💥 ${ab.self} себе`:""}`;if(ab.kind==="damageSelf")return`⚔ ${ab.amount??0} врагу · 💥 ${ab.self??0} себе`;if(ab.kind==="steal")return"⇠ украсть вражеский куб 1";if(ab.kind==="adjustPool")return`⚔ ${ab.amount??0} урона · ↑ усилить куб пула`;return ab.text}
function living(g:G,p?:P){return g.creatures.filter(c=>c.alive&&(!p||c.owner===p))}
function points(g:G,p:P){return living(g,p).reduce((n,c)=>n+c.card.glory,0)}
function targetEnemy(g:G,a:C){const p:P=a.owner==="A"?"B":"A";return living(g,p).sort((x,y)=>(x.hp-y.hp)||(y.card.glory-x.card.glory))[0]||null}
function targetHeal(g:G,a:C){return living(g,a.owner).sort((x,y)=>(y.card.hp-y.hp)-(x.card.hp-x.hp)||y.card.glory-x.card.glory)[0]||a}
function kill(g:G,id:string){const d=creature(g,id);if(!d)return g;const allies=living(g,d.owner).filter(x=>x.id!==id);const n=d.card.passive==="inherit2"?2:1;const keep=[...d.dice].sort((a,b)=>b.value-a.value).slice(0,n);let z=upd(g,id,c=>({...c,alive:false,hp:0,dice:[]}));keep.forEach((die,i)=>{const to=allies[i%Math.max(1,allies.length)];if(to)z=upd(z,to.id,c=>({...c,dice:[...c.dice,die]}))});return note(z,`${d.card.name} погибает; ${keep.length} куб(а) сохранено.`)}
function damage(g:G,id:string,n:number){let z=upd(g,id,c=>({...c,hp:Math.max(0,c.hp-n)}));const c=creature(z,id);z=note(z,`${c?.card.name} получает ${n} урона.`);return c&&c.hp<=0?kill(z,id):z}
function heal(g:G,id:string,n:number){const c=creature(g,id);return c?note(upd(g,id,x=>({...x,hp:Math.min(x.card.hp,x.hp+n)})),`${c.card.name} лечится на ${n}.`):g}
function amount(g:G,a:C,ab:Ability,t:C|null){let n=ab.amount??0;if(ab.bonusPool&&g.pool.filter(d=>d.type===ab.bonusPool!.type).length>=ab.bonusPool.count)n+=ab.bonusPool.bonus;if(ab.woundedBonus&&t&&t.hp<t.card.hp)n+=ab.woundedBonus;if(a.card.id==="collector"&&t?.dice.some(d=>d.value===1))n++;return n}
function use(g:G,ab:Ability){const a=creature(g,g.active);if(!a||g.used)return g;const p=pay(a,ab);if(!p)return g;const ids=new Set(p.map(d=>d.id));let z=upd(g,a.id,c=>({...c,dice:c.dice.filter(d=>!ids.has(d.id))}));z=note(z,`${a.card.name}: «${ab.name}».`);if(ab.kind==="damage"||ab.kind==="damageSelf"||ab.kind==="adjustPool"){const t=targetEnemy(z,a);if(t)z=damage(z,t.id,amount(z,a,ab,t));if(ab.kind==="damageSelf"&&creature(z,a.id)?.alive)z=damage(z,a.id,ab.self??0);if(ab.kind==="adjustPool"&&z.pool.length){const d=[...z.pool].sort((x,y)=>x.value-y.value)[0];const next=Math.min(3,d.value+1);z={...z,pool:z.pool.map(x=>x.id===d.id?{...x,value:next}:x)};z=note(z,`Общий пул: ${I[d.type]}${d.value} → ${I[d.type]}${next}.`)}}else if(ab.kind==="heal"){const t=targetHeal(z,a);z=heal(z,t.id,ab.amount??1);if(ab.self&&creature(z,a.id)?.alive)z=damage(z,a.id,ab.self)}else if(ab.kind==="steal"){const t=targetEnemy(z,a);const d=t?.dice.find(x=>x.value===1);if(t&&d){z=upd(z,t.id,c=>({...c,dice:c.dice.filter(x=>x.id!==d.id)}));z=upd(z,a.id,c=>({...c,dice:[...c.dice,d]}));z=note(z,`${a.card.name} крадёт ${I[d.type]}1.`)}}return{...z,used:true}}
function take(g:G,id:string){if(!g.needsDie)return g;const a=creature(g,g.active),d=g.pool.find(x=>x.id===id);if(!a||!d)return g;const had=a.dice.length>0;let z=upd(g,a.id,c=>({...c,dice:[...c.dice,d]}));z={...z,pool:z.pool.filter(x=>x.id!==id),needsDie:false};z=note(z,`${a.card.name} берёт ${I[d.type]}${d.value}.`);const enemy:P=a.owner==="A"?"B":"A";if(d.value===3&&living(z,enemy).some(c=>c.card.passive==="punish3"))z=damage(z,a.id,1);if(d.value===3&&had){const tax=living(z,enemy).find(c=>c.card.passive==="tax3"),aa=creature(z,a.id),one=aa?.dice.find(x=>x.value===1);if(tax&&aa&&one){z=upd(z,aa.id,c=>({...c,dice:c.dice.filter(x=>x.id!==one.id)}));z={...z,pool:[...z.pool,one]};z=note(z,"Сборщик долгов возвращает куб 1 в пул.")}}return z}
function nextTurn(g:G){let qq=g.queue.filter(id=>id!==g.active&&creature(g,id)?.alive);if(!qq.length){let z={...g,round:g.round+1,queue:q(g.creatures),used:false,needsDie:true};z.queue=q(z.creatures);z.active=z.queue[0]||null;return z}return{...g,queue:qq,active:qq[0],needsDie:true,used:false}}
function util(g:G,a:C,ab:Ability){if(!pay(a,ab))return-99;if(ab.kind==="heal"){const t=targetHeal(g,a);return Math.min(ab.amount??1,t.card.hp-t.hp)*1.5-(ab.self??0)}const t=targetEnemy(g,a);if(ab.kind==="steal")return t?.dice.some(d=>d.value===1)?3:0;const n=t?amount(g,a,ab,t):0;return n*2+(t&&n>=t.hp?4+t.card.glory:0)-(ab.self??0)}
function ai(g:G){const a=creature(g,g.active);if(!a||a.owner!=="B")return g;let z=g;if(z.needsDie){const d=[...z.pool].sort((x,y)=>{const sx=x.value+(a.card.abilities.some(ab=>pay({...a,dice:[...a.dice,x]},ab))?4:0)-(x.value===3&&living(z,"A").some(c=>c.card.passive==="punish3")?2:0);const sy=y.value+(a.card.abilities.some(ab=>pay({...a,dice:[...a.dice,y]},ab))?4:0)-(y.value===3&&living(z,"A").some(c=>c.card.passive==="punish3")?2:0);return sy-sx})[0];if(d)z=take(z,d.id)}const aa=creature(z,z.active);if(aa?.alive){const ab=[...aa.card.abilities].sort((x,y)=>util(z,aa,y)-util(z,aa,x))[0];if(ab&&util(z,aa,ab)>0)z=use(z,ab)}return nextTurn(note(z,"ИИ завершает активацию."))}
function start(seed:number){let[deck,s]=shuf(CARDS,seed);const cs:C[]=[];let nd=1,nc=1,pool:Die[]=[];for(const owner of ["A","B"] as P[])for(const card of deck.splice(0,4)){cs.push({id:`c${nc++}`,owner,card,hp:card.hp,alive:true,dice:[]});for(const type of card.dice){const[r,n]=rand(s);s=n;pool.push({id:`d${nd++}`,type,value:F[Math.floor(r*6)]})}}const queue=q(cs);return{cards:CARDS,creatures:cs,pool,queue,active:queue[0]||null,needsDie:true,used:false,round:1,log:["AI Arena: бой начался."],rng:s,nextDie:nd,nextC:nc,done:false} satisfies G}

export default function AiPage(){const[g,setG]=useState<G>(()=>start(12345));const[aSeed,setSeed]=useState("12345");const a=useMemo(()=>creature(g,g.active),[g]);useEffect(()=>{if(a?.owner==="B"&&!g.done){const t=setTimeout(()=>setG(x=>ai(x)),450);return()=>clearTimeout(t)}},[g.active,g.needsDie,g.used,g.done]);const finished=!living(g,"A").length||!living(g,"B").length;useEffect(()=>{if(finished&&!g.done)setG(x=>({...x,done:true,log:[`${points(x,"A")>=points(x,"B")?"Вы":"ИИ"} лидирует по славе ${points(x,"A")}:${points(x,"B")}.`,...x.log]}))},[finished,g.done]);return <main className="lab"><style>{CSS}</style><header><div><b>Dice Draft · AI Arena v0.4</b><h1>Быстрый бой против ИИ</h1><p>12 экспериментальных карт, 6 фракций. ИИ — локальная эвристика без API: быстро и бесплатно.</p></div><div><input value={aSeed} onChange={e=>setSeed(e.target.value)}/><button onClick={()=>setG(start(Number(aSeed)||12345))}>Новая арена</button><a href="/">← hot-seat</a></div></header><section className="bar"><strong>Вы ★{points(g,"A")}</strong><span>Раунд {g.round}</span><strong>ИИ ★{points(g,"B")}</strong></section><section className="panel"><h2>{g.done?"Тест завершён":a?`Ход: ${a.card.name} · ${a.owner==="A"?"Вы":"ИИ"}`:"—"}</h2><div className="event"><small>Что произошло</small><strong>{g.log[0]}</strong>{g.log[1]&&<span>{g.log[1]}</span>}</div><h3>Общий пул</h3><div className="pool">{g.pool.map(d=><button key={d.id} className={d.type} disabled={a?.owner!=="A"||!g.needsDie||g.done} onClick={()=>setG(x=>take(x,d.id))}>{I[d.type]}{d.value}</button>)}</div>{a?.owner==="A"&&!g.done&&<div className="actions">{g.needsDie?<p>Возьмите куб. Тройки сильные, но Каратель делает их опасными.</p>:<>{a.card.abilities.map(ab=><button key={ab.name} disabled={!pay(a,ab)||g.used} onClick={()=>setG(x=>use(x,ab))}><b>{ab.name}</b><small>{effectLabel(ab)}</small></button>)}<button className="end" onClick={()=>setG(x=>nextTurn(x))}>Завершить ход</button></>}</div>}<div className="board">{(["A","B"] as P[]).map(p=><div key={p}><h3>{p==="A"?"Ваши карты":"ИИ"}</h3><div className="row">{g.creatures.filter(c=>c.owner===p).map(c=><article key={c.id} className={`${c.id===g.active?"active":""} ${!c.alive?"dead":""}`}><small>{c.card.faction}</small><h4>{c.card.name}</h4><div>⚡{c.card.init} · ♥{c.hp}/{c.card.hp} · ★{c.card.glory}</div><div>{c.card.dice.map((t,i)=><i key={i}>{I[t]}</i>)}</div><div className="attached">{c.dice.map(d=><span key={d.id}>{I[d.type]}{d.value}</span>)}</div>{c.card.passive&&<p className="passive">{c.card.passive==="punish3"?"⚡ Вражеская 3 наносит 1 урон":c.card.passive==="inherit2"?"☠ При смерти передаёт 2 куба":"⚡ Налог на вражескую 3"}</p>}{c.card.abilities.map(ab=><p key={ab.name}><b>{ab.name}:</b> {ab.text}</p>)}</article>)}</div></div>)}</div></section><aside className="panel"><h3>Журнал</h3><ol>{g.log.slice(0,14).map((x,i)=><li key={i}>{x}</li>)}</ol></aside></main>}

const CSS=`.lab{min-height:100vh;background:#0f172a;color:#f8fafc;padding:18px;font-family:system-ui,sans-serif}.lab header,.panel,.bar{max-width:1400px;margin:0 auto 14px}.lab header{display:flex;justify-content:space-between;gap:18px}.lab header b{color:#fbbf24}.lab header h1{margin:5px 0}.lab header div:last-child{display:flex;gap:8px;align-items:flex-start;flex-wrap:wrap}.lab input,.lab button,.lab a{border:1px solid #475569;background:#1e293b;color:white;border-radius:9px;padding:9px;text-decoration:none}.bar,.panel{background:#172033;border:1px solid #334155;border-radius:14px;padding:14px}.bar{display:flex;justify-content:space-between}.pool,.actions,.attached{display:flex;gap:6px;flex-wrap:wrap}.pool button{font-size:19px;font-weight:800}.pool .attack{border-color:#ef4444}.pool .defense{border-color:#60a5fa}.pool .magic{border-color:#c084fc}.actions{margin:12px 0;padding:10px;background:#0b1220;border-radius:10px}.actions button{display:grid;gap:3px;text-align:left}.actions button small{color:#cbd5e1;font-size:11px;font-weight:700}.event{display:grid;gap:3px;margin:8px 0 14px;padding:10px 12px;border:1px solid #3b82a0;border-radius:11px;background:linear-gradient(135deg,#102536,#191c38)}.event small{color:#7dd3fc;font-weight:900;text-transform:uppercase;letter-spacing:.08em}.event strong{font-size:14px}.event span{color:#94a3b8;font-size:12px}.end{background:#f59e0b!important;color:#111827!important;font-weight:900}.board{display:grid;grid-template-columns:1fr 1fr;gap:14px}.row{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.row article{background:#111827;border:1px solid #334155;border-radius:12px;padding:10px}.row article.active{outline:3px solid #fbbf24}.row article.dead{opacity:.25}.row h4{margin:5px 0}.row i{font-style:normal}.row p{font-size:12px;color:#dbeafe}.passive{color:#fbbf24!important}.attached span{padding:3px 5px;background:#273449;border-radius:6px}.lab aside{max-height:300px;overflow:auto}.lab li{margin:5px 0;color:#cbd5e1}@media(max-width:800px){.lab{padding:9px}.lab header{flex-direction:column}.board{grid-template-columns:1fr}.row{grid-template-columns:repeat(2,minmax(0,1fr))}}`;
